-- ============================================================
-- ACONCN v2 — Supabase full sync (generated 2026-08-31)
-- Source of truth: assets/js/site-data.js (Config.USE_LOCAL_DATA = true)
-- Run once inside Supabase SQL Editor. Safe to re-run (idempotent UPSERT).
-- ============================================================
begin;

-- 1) Replace catalog tables with the authoritative local dataset
truncate table products restart identity cascade;
truncate table certifications restart identity cascade;
truncate table comparisons restart identity cascade;
truncate table news restart identity cascade;

-- ---------- products (56) ----------
insert into products (id, name, category, standard, load_class, price, description, specs, image, gallery, featured, sort_order, created_at) values
(1, 'AR-900H Heavy-Duty Round Manhole Cover (60T / F900)', 'manhole', 'EN 124 F900 · GB/T 23858', 'F900 (60T)', NULL, 'Our highest-capacity phenolic composite round cover, SMQ type-tested to 60 tonnes. Built for ports, airfields, container yards and main arterial roads. Flush-mount anti-settlement frame eliminates the "dark ring" around the frame.', '{"Model":"AR-900H","Type":"Heavy-duty round cover & frame","Clear Opening":"Ø900 mm","Overall Size":"Ø1100 mm","Height":"120 mm","Weight":"83 kg","Load Rating":"60 tonnes (F900)","Material":"Glass-fiber reinforced phenolic composite","Options":"With / without outer frame; custom cover markings"}'::jsonb, 'assets/images/products/refined/ar-900h.jpg', '[]'::jsonb, true, 1, '2026-08-31T00:00:00'),
(2, 'AR-700H Heavy-Duty Round Manhole Cover (40T / D400–E600)', 'manhole', 'EN 124 D400–E600 · GB/T 23858', 'D400–E600 (40T)', NULL, 'Flagship main-road cover, SMQ type-tested to 40 tonnes. The reinforced "heavy" version of the AR-700 line with a 100 mm deep frame — the standard choice for municipal arterial roads and heavy truck lanes.', '{"Model":"AR-700H","Type":"Heavy-duty round cover & frame","Clear Opening":"Ø700 mm","Overall Size":"Ø900 mm","Height":"100 mm","Weight":"47 kg","Load Rating":"40 tonnes (D400–E600)","Material":"Glass-fiber reinforced phenolic composite","Options":"With / without outer frame; custom cover markings"}'::jsonb, 'assets/images/products/refined/ar-700h.jpg', '[]'::jsonb, true, 2, '2026-08-31T00:00:00'),
(3, 'AR-750H Heavy-Duty Round Manhole Cover (30T / D400)', 'manhole', 'EN 124 D400 · GB/T 23858', 'D400 (30T)', NULL, 'Heavy-duty 750 mm round cover rated to 30 tonnes, widely used by telecom and information-network utilities on urban roads with mixed traffic.', '{"Model":"AR-750H","Type":"Heavy-duty round cover & frame","Clear Opening":"Ø750 mm","Overall Size":"Ø950 mm","Height":"80 mm","Weight":"34 kg","Load Rating":"30 tonnes (D400)","Material":"Glass-fiber reinforced phenolic composite","Options":"Custom utility markings (telecom / power / water)"}'::jsonb, 'assets/images/products/refined/ar-750h.jpg', '[]'::jsonb, false, 3, '2026-08-31T00:00:00'),
(4, 'AR-700B Round Manhole Cover with Frame (20T / C250)', 'manhole', 'EN 124 C250 · GB/T 23858', 'C250 (20T)', NULL, 'B-version round cover supplied complete with a 60 mm frame, rated to 20 tonnes for curb-side lanes, parking areas and residential distributor roads.', '{"Model":"AR-700B","Type":"Round cover with frame","Clear Opening":"Ø700 mm","Overall Size":"Ø850 mm","Height":"60 mm","Weight":"27 kg","Load Rating":"20 tonnes (C250)","Material":"Glass-fiber reinforced phenolic composite","Options":"Locking options; anti-slip surface"}'::jsonb, 'assets/images/products/refined/ar-700b.jpg', '[]'::jsonb, false, 4, '2026-08-31T00:00:00'),
(5, 'AR-700A Standard Round Manhole Cover (10T / B125)', 'manhole', 'EN 124 B125 · GB/T 23858', 'B125 (10T)', NULL, 'Light-frame 700 mm round cover for footways, pedestrian zones and light-vehicle areas. Same phenolic formulation as the heavy range in a slim 40 mm frame.', '{"Model":"AR-700A","Type":"Standard round cover & frame","Clear Opening":"Ø700 mm","Overall Size":"Ø850 mm","Height":"40 mm","Weight":"22 kg","Load Rating":"10 tonnes (B125)","Material":"Glass-fiber reinforced phenolic composite","Options":"Custom colors and embossed logos"}'::jsonb, 'assets/images/products/refined/ar-700a.jpg', '[]'::jsonb, false, 5, '2026-08-31T00:00:00'),
(6, 'AR-500 Compact Round Manhole Cover (5T / A15)', 'manhole', 'EN 124 A15 · GB/T 23858', 'A15 (5T)', NULL, 'Compact 500 mm inspection cover for valve chambers, garden drains and pedestrian areas where a small, lightweight cover is required.', '{"Model":"AR-500","Type":"Compact round cover & frame","Clear Opening":"Ø500 mm","Overall Size":"Ø700 mm","Height":"60 mm","Weight":"13 kg","Load Rating":"5 tonnes (A15)","Material":"Glass-fiber reinforced phenolic composite","Options":"Lift keys included"}'::jsonb, 'assets/images/products/refined/ar-500.jpg', '[]'::jsonb, false, 6, '2026-08-31T00:00:00'),
(7, 'AW-630 Round Gully Grating (20T / C250)', 'manhole', 'EN 124 C250 · GB/T 23858', 'C250 (20T)', NULL, '630 mm round gully top with anti-slip slot pattern, designed for road drainage connections. Balanced open area and wheel-load strength.', '{"Model":"AW-630","Type":"Round gully grating","Clear Opening":"Ø630 mm","Overall Size":"Ø780 mm","Height":"60 mm","Weight":"22 kg","Load Rating":"20 tonnes (C250)","Material":"Glass-fiber reinforced phenolic composite","Options":"Matching sump / bucket available"}'::jsonb, 'assets/images/products/refined/aw-630.jpg', '[]'::jsonb, true, 7, '2026-08-31T00:00:00'),
(8, 'AW-527 Round Gully Grating (5T / A15)', 'manhole', 'EN 124 A15 · GB/T 23858', 'A15 (5T)', NULL, '527 mm round gully grating for footways and light-duty drainage points.', '{"Model":"AW-527","Type":"Round gully grating","Clear Opening":"Ø527 mm","Overall Size":"Ø700 mm","Height":"40 mm","Weight":"13 kg","Load Rating":"5 tonnes (A15)","Material":"Glass-fiber reinforced phenolic composite","Options":"Custom slot layout"}'::jsonb, 'assets/images/products/refined/aw-527.jpg', '[]'::jsonb, false, 8, '2026-08-31T00:00:00'),
(9, 'AW-450H Heavy-Duty Round Gully Grating (5T)', 'manhole', 'EN 124 A15–B125 · GB/T 23858', 'A15–B125 (5T)', NULL, 'Reinforced 450 mm gully grating with deeper frame for small drainage catch points.', '{"Model":"AW-450H","Type":"Heavy-duty round gully grating","Clear Opening":"Ø450 mm","Overall Size":"Ø600 mm","Height":"40 mm","Weight":"10 kg","Load Rating":"5 tonnes","Material":"Glass-fiber reinforced phenolic composite","Options":"Anti-slip finish"}'::jsonb, 'assets/images/products/refined/aw-450h.jpg', '[]'::jsonb, false, 9, '2026-08-31T00:00:00'),
(10, 'AW-630R Round-Frame Gully Top with Square Insert', 'manhole', 'GB/T 23858', 'C250', NULL, 'Round outer frame with a square insert cover — a retrofit-friendly profile that matches existing round excavations while accepting square gully hardware.', '{"Model":"AW-630R","Type":"Round frame / square insert gully top","Clear Opening":"Ø630 mm","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"C250 class","Options":"Custom frame heights"}'::jsonb, 'assets/images/products/refined/aw-630r.jpg', '[]'::jsonb, false, 10, '2026-08-31T00:00:00'),
(11, 'AW-625F Square Gully Grating', 'manhole', 'GB/T 23858', 'B125–C250', NULL, 'Square-format gully grating for linear and point drainage in paved areas.', '{"Model":"AW-625F","Type":"Square gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"B125–C250 class","Options":"Custom open-area ratio"}'::jsonb, 'assets/images/products/refined/aw-625f.jpg', '[]'::jsonb, false, 11, '2026-08-31T00:00:00'),
(12, 'AW-633F Square Gully Grating', 'manhole', 'GB/T 23858', 'B125–C250', NULL, '633 mm square gully grating with reinforced rib structure for urban drainage.', '{"Model":"AW-633F","Type":"Square gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"B125–C250 class","Options":"Frame and sump options"}'::jsonb, 'assets/images/products/refined/aw-633f.jpg', '[]'::jsonb, false, 12, '2026-08-31T00:00:00'),
(13, 'AW-635L Channel Gully Grating', 'manhole', 'GB/T 23858', 'B125–C250', NULL, 'Linear channel grating profile for continuous drainage runs along curbs and portals.', '{"Model":"AW-635L","Type":"Channel / linear gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"B125–C250 class","Options":"Custom lengths"}'::jsonb, 'assets/images/products/refined/aw-635l.jpg', '[]'::jsonb, false, 13, '2026-08-31T00:00:00'),
(14, 'AW-640 Round Gully Grating', 'manhole', 'GB/T 23858', 'C250', NULL, '640 mm round gully grating, a common retrofit size for legacy municipal catch basins.', '{"Model":"AW-640","Type":"Round gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"C250 class","Options":"Matching frame"}'::jsonb, 'assets/images/products/refined/aw-640.jpg', '[]'::jsonb, false, 14, '2026-08-31T00:00:00'),
(15, 'AW-644F Square Gully Grating', 'manhole', 'GB/T 23858', 'C250', NULL, 'Heavy square gully grating for high-flow drainage points in parking decks and plazas.', '{"Model":"AW-644F","Type":"Square gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"C250 class","Options":"Anti-slip slots"}'::jsonb, 'assets/images/products/refined/aw-644f.jpg', '[]'::jsonb, false, 15, '2026-08-31T00:00:00'),
(16, 'AW-645L Channel Gully Grating', 'manhole', 'GB/T 23858', 'C250', NULL, 'Wide linear grating for trench drains and port-area surface water control.', '{"Model":"AW-645L","Type":"Channel / linear gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"C250 class","Options":"Custom lengths and frames"}'::jsonb, 'assets/images/products/refined/aw-645l.jpg', '[]'::jsonb, false, 16, '2026-08-31T00:00:00'),
(17, 'AW-655 Round Gully Grating', 'manhole', 'GB/T 23858', 'C250', NULL, '655 mm round gully top for oversized catch basins and high-rainfall regions.', '{"Model":"AW-655","Type":"Round gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"C250 class","Options":"Sump bucket"}'::jsonb, 'assets/images/products/refined/aw-655.jpg', '[]'::jsonb, false, 17, '2026-08-31T00:00:00'),
(18, 'AW-740 Heavy-Duty Round Gully Grating', 'manhole', 'GB/T 23858', 'D400', NULL, 'Large 740 mm gully grating engineered for main-road carriageway drainage.', '{"Model":"AW-740","Type":"Heavy-duty round gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"D400 class","Options":"Bolted frame option"}'::jsonb, 'assets/images/products/refined/aw-740.jpg', '[]'::jsonb, false, 18, '2026-08-31T00:00:00'),
(19, 'AW-8380 Long Linear Gully Grating (380×800, 20T)', 'manhole', 'EN 124 C250 · GB/T 23858', 'C250 (20T)', NULL, 'Rectangular 380×800 mm longitudinal grating for curb-line channel drains, rated to 20 tonnes.', '{"Model":"AW-8380","Type":"Linear gully grating","Overall Size":"380 × 800 mm","Height":"60 mm","Weight":"22 kg","Load Rating":"20 tonnes (C250)","Material":"Glass-fiber reinforced phenolic composite","Options":"Interlocking sections"}'::jsonb, 'assets/images/products/refined/aw-8380.jpg', '[]'::jsonb, false, 19, '2026-08-31T00:00:00'),
(20, 'AW-20B Compact Gully Grating', 'manhole', 'GB/T 23858', 'A15–B125', NULL, 'Small B-series gully grating for balcony drains, utility trenches and light-traffic zones.', '{"Model":"AW-20B","Type":"Compact gully grating","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"A15–B125 class","Options":"Custom colors"}'::jsonb, 'assets/images/products/refined/aw-20b.jpg', '[]'::jsonb, false, 20, '2026-08-31T00:00:00'),
(21, 'AA-1314 Large Square Access Cover (1300×1400, 10T)', 'manhole', 'EN 124 B125 · GB/T 23858', 'B125 (10T)', NULL, 'Oversized double-leaf square cover for large valve halls, pump stations and utility chambers that need personnel and equipment access.', '{"Model":"AA-1314","Type":"Large square access cover","Overall Size":"1300 × 1400 mm","Height":"40 mm","Weight":"65 kg","Load Rating":"10 tonnes (B125)","Material":"Glass-fiber reinforced phenolic composite","Options":"Gas-spring assist; multi-leaf"}'::jsonb, 'assets/images/products/refined/aa-1314.jpg', '[]'::jsonb, true, 21, '2026-08-31T00:00:00'),
(22, 'AA-178 Hong Kong Lands Department Pattern Cover', 'manhole', 'HK Lands Dept spec · GB/T 23858', 'B125–C250', NULL, 'Square cover produced to the Hong Kong Lands Department pattern — part of ACONCN''s long-running supply record for Hong Kong public works.', '{"Model":"AA-178","Type":"Square utility cover (HK pattern)","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"B125–C250 class","Options":"HK-standard embossed markings"}'::jsonb, 'assets/images/products/refined/aa-178.jpg', '[]'::jsonb, false, 22, '2026-08-31T00:00:00'),
(23, 'AA-380 Buried Gas Valve Protection Box', 'manhole', 'GB/T 23858', 'A15', NULL, 'Surface-mounted composite valve box protecting buried gas valves and cocks. Non-sparking, corrosion-proof and marked for gas utility identification.', '{"Model":"AA-380","Type":"Buried gas valve box","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"A15 class (pedestrian / verge)","Options":"Custom utility markings and colors"}'::jsonb, 'assets/images/products/refined/aa-380-gas.jpg', '[]'::jsonb, false, 23, '2026-08-31T00:00:00'),
(24, 'AA-8A Round Tree Grate', 'manhole', 'GB/T 23858', 'Pedestrian', NULL, 'Segmental round tree grate protecting tree pits on sidewalks and plazas. Opens for tree growth, keeps heels and wheels from catching, and never rots or rusts.', '{"Model":"AA-8A","Type":"Round tree grate (segmented)","Material":"Glass-fiber reinforced phenolic composite","Finish":"Anti-slip, UV-stable","Options":"Adjustable inner opening; custom colors"}'::jsonb, 'assets/images/products/refined/aa-8a-tree-grate-round.jpg', '[]'::jsonb, false, 24, '2026-08-31T00:00:00'),
(25, 'AA-8B Square Tree Grate', 'manhole', 'GB/T 23858', 'Pedestrian', NULL, 'Segmental square tree grate for formal street-tree planting grids. Bolted segments ship flat and assemble on site.', '{"Model":"AA-8B","Type":"Square tree grate (segmented)","Material":"Glass-fiber reinforced phenolic composite","Finish":"Anti-slip, UV-stable","Options":"Custom dimensions and logos"}'::jsonb, 'assets/images/products/refined/aa-8b-tree-grate-square.jpg', '[]'::jsonb, false, 25, '2026-08-31T00:00:00'),
(26, 'AB-750A Split-Type Water Meter Box (750×500)', 'manhole', 'GB/T 23858', 'A15–B125', NULL, 'Two-piece (A/B split) water meter chamber cover giving meter readers full access without lifting a single heavy slab.', '{"Model":"AB-750A","Type":"Split water meter box","Overall Size":"750 × 500 mm","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"A15–B125 class","Options":"Hinged leaf; locking latch"}'::jsonb, 'assets/images/products/refined/ab-750a.jpg', '[]'::jsonb, false, 26, '2026-08-31T00:00:00'),
(27, 'AF-535 Square Recessed Access Cover', 'manhole', 'GB/T 23858', 'B125', NULL, '535 mm square recessed cover designed to be paved or tiled over for an invisible finish in premium pavements and indoor plant rooms.', '{"Model":"AF-535","Type":"Square recessed access cover","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"B125 class","Options":"Tile-in / paving-in finish"}'::jsonb, 'assets/images/products/refined/af-535.jpg', '[]'::jsonb, false, 27, '2026-08-31T00:00:00'),
(28, 'AA-165 Small Square Utility Cover', 'manhole', 'GB/T 23858', 'A15', NULL, 'Small 165 mm square access cover for stop-taps, cable junctions and clean-out points.', '{"Model":"AA-165","Type":"Small square utility cover","Material":"Glass-fiber reinforced phenolic composite","Load Rating":"A15 class","Options":"Custom markings"}'::jsonb, 'assets/images/products/refined/aa-165.jpg', '[]'::jsonb, false, 28, '2026-08-31T00:00:00'),
(29, 'DN25 Pipe Repair Clamp (1″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Full-seal bolted repair clamp for burst and leaking DN25 (1 inch) pipes. Ductile-iron body, EPDM sealing gasket and stainless bolts — installs under pressure without cutting the main.', '{"Model":"DN25","Nominal Bore":"DN25 (1″)","Type":"Straight full-seal repair clamp","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn25.gif', '[]'::jsonb, false, 29, '2026-08-31T00:00:00'),
(30, 'DN32 Pipe Repair Clamp (1¼″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Full-seal repair clamp for DN32 (1¼ inch) service lines. Restores pipe integrity in minutes with no hot work.', '{"Model":"DN32","Nominal Bore":"DN32 (1¼″)","Type":"Straight full-seal repair clamp","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn32.gif', '[]'::jsonb, false, 30, '2026-08-31T00:00:00'),
(31, 'DN40 Pipe Repair Clamp (1½″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Full-seal repair clamp for DN40 (1½ inch) distribution pipes. 360° gasket wrap gives a positive seal even on pitted, out-of-round pipe.', '{"Model":"DN40","Nominal Bore":"DN40 (1½″)","Type":"Straight full-seal repair clamp","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn40.gif', '[]'::jsonb, false, 31, '2026-08-31T00:00:00'),
(32, 'DN50 Pipe Repair Clamp (2″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Our most frequently ordered size — full-seal clamp for DN50 (2 inch) building service and industrial piping.', '{"Model":"DN50","Nominal Bore":"DN50 (2″)","Type":"Straight full-seal repair clamp","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn50.gif', '[]'::jsonb, false, 32, '2026-08-31T00:00:00'),
(33, 'DN65 Pipe Repair Clamp (2½″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Full-seal clamp for DN65 (2½ inch) pipes — a common size in process cooling and fire-service laterals.', '{"Model":"DN65","Nominal Bore":"DN65 (2½″)","Type":"Straight full-seal repair clamp","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn65.gif', '[]'::jsonb, false, 33, '2026-08-31T00:00:00'),
(34, 'DN80 Pipe Repair Clamp (3″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Full-seal repair clamp for DN80 (3 inch) distribution mains. Two-piece shell allows fitting without pipe disassembly.', '{"Model":"DN80","Nominal Bore":"DN80 (3″)","Type":"Straight full-seal repair clamp","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn80.gif', '[]'::jsonb, false, 34, '2026-08-31T00:00:00'),
(35, 'DN100 Pipe Repair Clamp (4″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN16', NULL, 'Workhorse clamp for DN100 (4 inch) municipal and industrial water lines. Tapped / tee versions available for branch connections.', '{"Model":"DN100","Nominal Bore":"DN100 (4″)","Type":"Straight full-seal repair clamp (tee version on request)","Working Pressure":"PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn100.gif', '[]'::jsonb, false, 35, '2026-08-31T00:00:00'),
(36, 'DN150 Pipe Repair Clamp (6″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN10–PN16', NULL, 'Heavy full-seal clamp for DN150 (6 inch) trunk mains. Reinforced lugs and double-row bolts keep the seal under surge pressure.', '{"Model":"DN150","Nominal Bore":"DN150 (6″)","Type":"Straight full-seal repair clamp (tee version on request)","Working Pressure":"PN10–PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn150.gif', '[]'::jsonb, false, 36, '2026-08-31T00:00:00'),
(37, 'DN200 Pipe Repair Clamp (8″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN10–PN16', NULL, 'Large-bore full-seal clamp for DN200 (8 inch) transmission mains. The hinged two-shell design lets a two-man crew close a burst main without lifting equipment.', '{"Model":"DN200","Nominal Bore":"DN200 (8″)","Type":"Straight full-seal repair clamp (tee version on request)","Working Pressure":"PN10–PN16","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn200.gif', '[]'::jsonb, true, 37, '2026-08-31T00:00:00'),
(38, 'DN250 Pipe Repair Clamp (10″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN10', NULL, 'Full-seal clamp for DN250 (10 inch) water and wastewater mains. Wide gasket bridges corroded sections up to the clamp length.', '{"Model":"DN250","Nominal Bore":"DN250 (10″)","Type":"Straight full-seal repair clamp (tee version on request)","Working Pressure":"PN10","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn250.gif', '[]'::jsonb, false, 38, '2026-08-31T00:00:00'),
(39, 'DN300 Pipe Repair Clamp (12″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN10', NULL, 'Full-seal clamp for DN300 (12 inch) major transmission pipelines. Triple bolt rows and bridge plates available for long split sections.', '{"Model":"DN300","Nominal Bore":"DN300 (12″)","Type":"Straight full-seal repair clamp (tee version on request)","Working Pressure":"PN10","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn300.gif', '[]'::jsonb, false, 39, '2026-08-31T00:00:00'),
(40, 'DN400 Pipe Repair Clamp (16″ Full-Seal Coupling)', 'repair-clamps', 'ISO / EN pipeline fitting', 'PN10', NULL, 'Largest standard full-seal clamp for DN400 (16 inch) trunk mains and industrial headers. Engineered for emergency response teams that need a permanent, pressure-rated repair.', '{"Model":"DN400","Nominal Bore":"DN400 (16″)","Type":"Straight full-seal repair clamp (tee version on request)","Working Pressure":"PN10","Body":"Ductile cast iron, epoxy coated","Gasket":"EPDM (NBR on request)","Bolts":"Stainless steel 304","Pipe Compatibility":"Steel / ductile iron / PVC / PE"}'::jsonb, 'assets/images/products/repair-clamps/dn400.gif', '[]'::jsonb, false, 40, '2026-08-31T00:00:00'),
(41, 'AC-089300P Belt Conveyor Carrier Roller (Ø89×300, P-Seal)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Precision steel carrier idler roller, Ø89 mm tube × 300 mm face width with the P-series labyrinth seal configuration. Low runout, low rotation resistance and long bearing life for bulk-material belt conveyors.', '{"Model":"AC-089300P","Tube Diameter":"Ø89 mm","Roller Length":"300 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, triple labyrinth seal","Bearings":"Deep-groove ball bearings (sealed)","Configuration":"P-series seal; carry / return idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-089300p.jpg', '[]'::jsonb, false, 41, '2026-08-31T00:00:00'),
(42, 'AC-089750 Belt Conveyor Return Roller (Ø89×750)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Ø89 × 750 mm long-face roller typically deployed as a return (lower) idler on wide belt conveyors. Balanced tube and concentric bearing seats prevent belt wander.', '{"Model":"AC-089750","Tube Diameter":"Ø89 mm","Roller Length":"750 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, labyrinth seal","Bearings":"Deep-groove ball bearings (sealed)","Configuration":"Return / parallel idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-089750.jpg', '[]'::jsonb, false, 42, '2026-08-31T00:00:00'),
(43, 'AC-089945 Belt Conveyor Return Roller (Ø89×945)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Ø89 × 945 mm return roller for high-capacity, wide-belt conveyor lines in ports, power plants and aggregate yards.', '{"Model":"AC-089945","Tube Diameter":"Ø89 mm","Roller Length":"945 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, labyrinth seal","Bearings":"Deep-groove ball bearings (sealed)","Configuration":"Return / parallel idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-089945.jpg', '[]'::jsonb, false, 43, '2026-08-31T00:00:00'),
(44, 'AC-108300E Belt Conveyor Carrier Roller (Ø108×300, E-Bearing)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Ø108 mm heavy-gauge carrier roller with the E-series bearing configuration for troughing sets on medium and heavy belt conveyors.', '{"Model":"AC-108300E","Tube Diameter":"Ø108 mm","Roller Length":"300 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, multi-stage labyrinth seal","Bearings":"E-series sealed deep-groove ball bearings","Configuration":"Troughing carry idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-108300e.jpg', '[]'::jsonb, false, 44, '2026-08-31T00:00:00'),
(45, 'AC-108380 Belt Conveyor Carrier Roller (Ø108×380)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Our standard Ø108 × 380 mm troughing carrier — the workhorse roller for B1000-class belt conveyors in mining and bulk handling.', '{"Model":"AC-108380","Tube Diameter":"Ø108 mm","Roller Length":"380 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, labyrinth seal","Bearings":"Deep-groove ball bearings (sealed)","Configuration":"Troughing carry idler (35° / 45° sets)","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-108380.jpg', '[]'::jsonb, true, 45, '2026-08-31T00:00:00'),
(46, 'AC-108740 Belt Conveyor Return Roller (Ø108×740)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Ø108 × 740 mm return roller with reinforced shaft for long-span return idler frames.', '{"Model":"AC-108740","Tube Diameter":"Ø108 mm","Roller Length":"740 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, labyrinth seal","Bearings":"Deep-groove ball bearings (sealed)","Configuration":"Return / parallel idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-108740.jpg', '[]'::jsonb, false, 46, '2026-08-31T00:00:00'),
(47, 'AC-108110P Belt Conveyor Return Roller (Ø108×1100, P-Seal)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Heavy-duty', NULL, 'Long Ø108 × 1100 mm return roller with P-series dust- and water-proof seal train, built for outdoor, abrasive environments.', '{"Model":"AC-108110P","Tube Diameter":"Ø108 mm","Roller Length":"1100 mm","Tube":"Precision welded steel tube, anti-corrosion coated","Bearing Housing":"Cold-pressed steel, P-series labyrinth seal","Bearings":"Deep-groove ball bearings (sealed)","Configuration":"Return / parallel idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-108110p.jpg', '[]'::jsonb, false, 47, '2026-08-31T00:00:00'),
(48, 'AC-133380P Heavy Belt Conveyor Carrier Roller (Ø133×380, P-Seal)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Extra heavy-duty', NULL, 'Ø133 mm thick-wall carrier roller for heavy-load, high-tonnage conveyor systems — crushers, stockyards and ship loaders.', '{"Model":"AC-133380P","Tube Diameter":"Ø133 mm","Roller Length":"380 mm","Tube":"Thick-wall precision steel tube","Bearing Housing":"Cold-pressed steel, P-series labyrinth seal","Bearings":"Oversized sealed deep-groove bearings","Configuration":"Troughing carry idler","Runout Tolerance":"≤ 0.5 mm"}'::jsonb, 'assets/images/products/rollers/ac-133380p.jpg', '[]'::jsonb, false, 48, '2026-08-31T00:00:00'),
(49, 'AC-1331600T Extra-Long Conveyor Roller (Ø133×1600, T-Config)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Extra heavy-duty', NULL, 'Extra-long Ø133 × 1600 mm roller in the T-series configuration, for ultra-wide belts and special impact / garland stations.', '{"Model":"AC-1331600T","Tube Diameter":"Ø133 mm","Roller Length":"1600 mm","Tube":"Thick-wall precision steel tube","Bearing Housing":"Cold-pressed steel, multi-stage seal","Bearings":"Oversized sealed deep-groove bearings","Configuration":"T-series; return / garland idler","Runout Tolerance":"≤ 0.6 mm"}'::jsonb, 'assets/images/products/rollers/ac-1331600t.jpg', '[]'::jsonb, false, 49, '2026-08-31T00:00:00'),
(50, 'AC-159740 Extra-Heavy Conveyor Carrier Roller (Ø159×740)', 'rollers', 'GB/T 10595 · DIN 22107 compatible', 'Extra heavy-duty', NULL, 'Largest Ø159 mm carrier roller for the heaviest mining and port conveyor duties, absorbing high impact at loading points.', '{"Model":"AC-159740","Tube Diameter":"Ø159 mm","Roller Length":"740 mm","Tube":"Extra thick-wall precision steel tube","Bearing Housing":"Heavy pressed steel, labyrinth seal","Bearings":"Large sealed deep-groove bearings","Configuration":"Impact / troughing carry idler","Runout Tolerance":"≤ 0.6 mm"}'::jsonb, 'assets/images/products/rollers/ac-159740.jpg', '[]'::jsonb, false, 50, '2026-08-31T00:00:00'),
(51, 'AF-500 FRP Sloped-Lid Waste Bin', 'outdoor', 'Municipal street furniture', 'Weatherproof', NULL, 'One-piece glass-fiber reinforced waste bin with a self-closing sloped lid — rain runs off, waste stays hidden, graffiti cleans off. Deployed in parks, promenades and transit plazas.', '{"Model":"AF-500","Type":"Sloped-lid outdoor waste bin","Material":"Fiberglass reinforced composite (FRP/SMC)","Finish":"UV-stable gelcoat, custom RAL colors","Features":"Rust-proof, waterproof lid, lift-out inner liner","Mounting":"Free-standing or bolt-down","Customization":"Embossed / printed logo"}'::jsonb, 'assets/images/products/outdoor/af-500-bin.jpg', '[]'::jsonb, true, 51, '2026-08-31T00:00:00'),
(52, 'AL-700 Large FRP Sloped-Lid Waste Bin', 'outdoor', 'Municipal street furniture', 'Weatherproof', NULL, 'Larger-capacity 700-class sloped-lid bin for high-traffic locations. Proven ACONCN Happy-Orient pattern supplied to waterfront and theme-park operators.', '{"Model":"AL-700","Type":"Large sloped-lid outdoor waste bin","Material":"Fiberglass reinforced composite (FRP/SMC)","Finish":"UV-stable gelcoat, custom RAL colors","Features":"High capacity, rain-shedding lid, replaceable liner","Mounting":"Free-standing or bolt-down","Customization":"Full customer branding"}'::jsonb, 'assets/images/products/outdoor/al-700-bin.gif', '[]'::jsonb, false, 52, '2026-08-31T00:00:00'),
(53, 'Three-Stream FRP Sorting Bin (Custom EASTECH Build)', 'outdoor', 'Municipal street furniture', 'Weatherproof', NULL, 'Stacked three-compartment recycling / sorting bin for source-separated waste streams. Delivered as a custom-branded build; compartment layout and labeling are fully configurable.', '{"Model":"3-Tier Sorting Bin","Type":"Three-stream sorting / recycling bin","Material":"Fiberglass reinforced composite (FRP/SMC)","Streams":"3 compartments (configurable)","Finish":"UV-stable gelcoat, custom colors & labels","Mounting":"Free-standing or bolt-down","Customization":"Logo, stream labels, aperture shapes"}'::jsonb, 'assets/images/products/outdoor/bin-3tier.gif', '[]'::jsonb, false, 53, '2026-08-31T00:00:00'),
(54, 'Square FRP Street Planter 500 (Lotus Series)', 'outdoor', 'Municipal street furniture', 'Weatherproof', NULL, 'One-piece molded square planter with rolled safety rim, raised feet for drainage and hand-painted finish. Lightweight versus concrete, will not crack, rot or rust — the ACONCN lotus-decor classic.', '{"Model":"Planter-500","Type":"Square outdoor planter","Material":"Fiberglass reinforced composite (FRP/SMC)","Finish":"Hand-finished gelcoat, custom artwork","Features":"Drainage feet, frost-proof, UV-stable","Mounting":"Free-standing","Customization":"Color, relief artwork, logo"}'::jsonb, 'assets/images/products/outdoor/planter-500.jpg', '[]'::jsonb, false, 54, '2026-08-31T00:00:00'),
(55, 'Custom Theme-Park Planter — Ocean Park Hong Kong Case', 'outdoor', 'Custom project build', 'Weatherproof', NULL, 'Custom-molded branded planter series manufactured for Ocean Park Hong Kong — customer-specified color, embossed bilingual park name and integrated planting liner. A reference for custom theme-park and municipal programs.', '{"Model":"Custom (Ocean Park reference)","Type":"Branded square planter","Material":"Fiberglass reinforced composite (FRP/SMC)","Finish":"Custom green gelcoat, embossed logo","Features":"Integrated liner, weatherproof, low maintenance","MOQ":"Custom projects from 30 pcs","Customization":"Shape, color, embossed / printed branding"}'::jsonb, 'assets/images/products/outdoor/planter-ocean-park.png', '[]'::jsonb, false, 55, '2026-08-31T00:00:00'),
(56, 'Custom Theme-Park Planter — Hong Kong Disneyland Case', 'outdoor', 'Custom project build', 'Weatherproof', NULL, 'Custom-molded planter produced for the Hong Kong Disneyland program, showing the depth of bespoke branding available — themed colors, embossed wordmarks and durable outdoor gelcoat that stays vivid for years.', '{"Model":"Custom (Disneyland reference)","Type":"Branded square planter","Material":"Fiberglass reinforced composite (FRP/SMC)","Finish":"Custom themed gelcoat, embossed wordmark","Features":"Integrated liner, weatherproof, impact-resistant","MOQ":"Custom projects from 30 pcs","Customization":"Shape, color, themed artwork and branding"}'::jsonb, 'assets/images/products/outdoor/planter-disney.png', '[]'::jsonb, false, 56, '2026-08-31T00:00:00');

-- ---------- certifications (6) ----------
insert into certifications (id, title, issuer, cert_number, issue_date, description, image, sort_order) values
(1, 'SMQ Type-Test Report — 60 Tonne Load (AR-900H)', 'Shenzhen Academy of Metrology & Quality Inspection (SMQ)', 'WT201032210664SWT1', '2022-07-01', 'Independent laboratory type test verifying the AR-900H phenolic composite cover assembly to a 60-tonne proof load — the F900 performance class used on ports, airfields and the heaviest arterial roads.', 'assets/images/certs/smq-60t.jpg', 1),
(2, 'SMQ Type-Test Report — 40 Tonne Load (AR-700H)', 'Shenzhen Academy of Metrology & Quality Inspection (SMQ)', 'WT20103221066480WT1', '2022-07-01', 'Independent type test of the AR-700H main-road cover assembly to a 40-tonne proof load, covering D400–E600 carriageway duty with permanent-set and crack criteria recorded.', 'assets/images/certs/smq-40t.jpg', 2),
(3, 'ISO 9001 Quality Management Certification', 'QA International Certification Ltd.', 'QA-IQMS-0213', '2013-02-18', 'Quality management system certification covering the design and manufacture of composite manhole covers, drain gratings and access covers, audited against ISO 9001.', 'assets/images/certs/qa-iso9001.jpg', 3),
(4, 'ISO 14001 Environmental Management Certification', 'QA International Certification Ltd.', 'QA-IEMS-0213', '2013-02-18', 'Environmental management system certification — evidence of controlled, low-waste production and the recycled-material content of our phenolic composite line.', 'assets/images/certs/qa-iso14001.jpg', 4),
(5, 'Hong Kong Green Label Certificate', 'Hong Kong Green Label Scheme (GL-HK)', 'HK GL-03184', '2016-08-01', 'Hong Kong eco-label recognition for environmental steel-fiberglass products, supporting green-procurement requirements in Hong Kong public works.', 'assets/images/certs/hk-green-label.jpg', 5),
(6, 'ISO 9001 Quality System Certificate (UCS)', 'Universal Certification Systems (UCS)', '00121Q12345R0M', '2014-12-09', 'Quality management system certificate for manhole cover and gully grate production, issued under the GB/T 19001 (idt ISO 9001) scheme.', 'assets/images/certs/ucs-iso9001.jpg', 6);

-- ---------- comparisons (8) ----------
insert into comparisons (id, feature, composite, standard_composite, cast_iron, sort_order) values
(1, 'Weight', '70% lighter — D400 ~35 kg, two-person install', 'Heavier low-grade mix — D400 ~55 kg', 'Very heavy — D400 ~120 kg, lifting gear needed', 1),
(2, 'Load Performance', 'SMQ-verified 40T / 60T proof loads (D400–F900)', 'Variable batch quality; ratings often unverified', 'High nominal strength but brittle fracture on impact', 2),
(3, 'Settlement / "Dark Ring"', 'Flush anti-settlement frame — stays level with the road', 'Thin frame sinks under repeated wheel loads', 'Heavy rocking frame fractures surrounding asphalt', 3),
(4, 'Corrosion Resistance', 'Zero rust; resistant to salts, acids and UV', 'No rust, but poor UV / chemical resistance over time', 'Rusts continuously; protective coating wears off', 4),
(5, 'Anti-Theft', 'No scrap value — inherently theft-proof', 'Low scrap value, but cheap units are easily smashed', 'High scrap value — routinely stolen worldwide', 5),
(6, 'Anti-Skid Surface', 'Molded anti-slip tread pattern, wet or dry', 'Smooth wear surface polishes slippery', 'Aggressive when new, wears smooth as it rusts', 6),
(7, 'Lifespan', '30+ years with near-zero maintenance', '15–20 years, highly manufacturer-dependent', '10–15 years before corrosion failure', 7),
(8, 'Cost Over Lifetime', 'Lowest TCO — virtually no replacement cycles', 'Medium TCO — periodic replacement', 'Highest TCO — repeated replacement & roadworks', 8);

-- ---------- news (8) ----------
insert into news (id, category, title, excerpt, content, image, author, sort_order, created_at) values
(1, 'company', '14 Years and Counting: A 2012 ACONCN Cover Still Flush on a Shenzhen Main Road', 'Dated December 2012 and still perfectly level with the asphalt — one Shenzhen drainage cover is a 14-year field test our competitors would rather not talk about.', '<p>Most marketing claims about product lifespan are extrapolated in a laboratory. Ours are driving over them every day.</p><p>In December 2012, ACONCN (Happy Orient Industrial) phenolic composite drainage covers were installed on a Shenzhen municipal carriageway. The cover in the photograph still carries mixed urban traffic — buses, trucks and passenger cars — fourteen years later. Three things are worth noting for engineers who specify access covers:</p><ul><li><strong>It is still flush.</strong> There is no settlement ring, no exposed frame lip and no asphalt fracture around the frame — the classic "dark ring" that signals a failing cover installation.</li><li><strong>There is no corrosion.</strong> A cast-iron cover at the same age would show active rust bleeding through the surrounding pavement. The phenolic composite surface is chemically inert.</li><li><strong>The anti-skid tread is still legible</strong>, including the original standard marking GB/T 23858 and the installation date cast into the cover.</li></ul><p>This is the field evidence behind our 10-year replacement guarantee: a cover that holds its frame geometry does not transmit impact loads into the surrounding asphalt, and that single fact removes the single most common failure mode of municipal access covers.</p><p>Specifiers comparing cover systems for main-road duty are welcome to request the location, the SMQ load-test reports, and sample units for their own evaluation.</p>', 'assets/images/comparison/aconcn-flush.jpg', 'ACONCN Engineering', 1, '2026-08-20T09:00:00'),
(2, 'product', 'Anti-Settlement Flush Installation: How ACONCN Covers Eliminate the "Dark Ring"', 'The ugly black patch around a manhole is not a paving problem — it is a cover-frame problem. Here is the mechanics, and how a flush frame design stops it.', '<p>Drive any urban road and you will see them: dark circular scars cut into the asphalt around manhole covers. Maintenance crews patch them; they always come back. The reason is structural, and it starts below the surface.</p><h5>Why the dark ring forms</h5><p>A conventional cover sits in a narrow rigid frame. When a wheel crosses, the cover deflects and rocks inside its seating; every rocking cycle pumps the frame against the asphalt. Water enters the fracture plane, traffic compresses it, and within months a ring of fatigued asphalt — the "dark ring" — breaks down around the frame.</p><h5>The flush-mount fix</h5><p>ACONCN covers use a deep, wide-flange anti-settlement frame that transfers wheel loads into the structural course rather than the surface course:</p><ul><li>Deep frame skirts (100 mm on the AR-700H, 120 mm on the AR-900H) lock into the road build-up</li><li>A broad load-spreading flange removes the stress concentration at the frame edge</li><li>A machined cover-to-frame seat eliminates rocking, so there is no pumping action</li><li>The finished cover sits flush within 1–2 mm of the road surface</li></ul><p>The photograph shows the result on a live carriageway: no ring, no lip, no patch — years after installation.</p><h5>What to ask your supplier</h5><p>Request frame depth, flange width and a cover-seat tolerance. If a supplier cannot quantify them, the dark ring is already scheduled into your maintenance budget.</p>', 'assets/images/story/story-flush-cover.jpg', 'ACONCN Engineering', 2, '2026-08-12T09:00:00'),
(3, 'industry', 'EN 124 Load Classes A15 to F900: A No-Nonsense Selection Guide', 'Picking a cover by price instead of load class is how main roads end up with footway-grade covers. Here is exactly what A15 through F900 mean — and where each belongs.', '<p>EN 124 groups gully tops and manhole tops into six load classes according to their place of installation. Choosing one class above what you need wastes money; one class below generates replacement cycles and liability.</p><h5>The six classes</h5><ul><li><strong>A15 (15 kN)</strong> — areas exclusively for pedestrians and cyclists: garden paths, verges, indoor plant rooms.</li><li><strong>B125 (125 kN)</strong> — footways, pedestrian zones and car parks accessible only to light vehicles.</li><li><strong>C250 (250 kN)</strong> — gutter-side areas and curb zones, residential distributor roads, parking decks.</li><li><strong>D400 (400 kN)</strong> — carriageways, hard shoulders and most urban roads open to all traffic.</li><li><strong>E600 (600 kN)</strong> — areas imposing large wheel loads: ports, docks, heavy haul roads.</li><li><strong>F900 (900 kN)</strong> — exceptionally heavy-duty areas: aircraft pavements, container terminals, heavy industrial floors.</li></ul><h5>Common specification mistakes</h5><p>The most frequent error is fitting B125 or C250 covers on a D400 carriageway to save unit cost — a decision that typically reverses itself within two to three years through cover fracture and frame settlement. The second is ignoring the frame: a D400 cover in a thin frame still fails at the frame-to-road interface.</p><h5>How ACONCN maps to EN 124</h5><p>Our phenolic range spans A15 through F900 equivalents, with independent SMQ proof-load testing at 40 and 60 tonnes. Tell us the installation zone and traffic mix and we will specify the smallest class that does the job safely — not the largest class we can sell you.</p>', 'assets/images/products/refined/ar-900h.jpg', 'ACONCN Engineering', 3, '2026-07-28T09:00:00'),
(4, 'product', 'Three-Way Showdown: ACONCN Phenolic vs Standard Composite vs Cast Iron', 'Not all composite covers are the same material, and "cheaper than iron" is not a specification. A field-level comparison across the metrics that actually fail.', '<p>"Composite" covers now compete at every price point, but the word spans everything from glass-filled phenolic engineered for carriageways to low-grade resin-and-sand mixes that belong on a footway. Buyers comparing quotes line-by-line are often comparing three different products.</p><h5>Material hierarchy</h5><p><strong>Cast iron</strong> is strong but heavy, corrosive and theft-prone. <strong>Standard composite</strong> (cheap BMC/resin mixes) removes rust and scrap value but varies wildly in fiber content and load endurance. <strong>Glass-fiber reinforced phenolic</strong> — the ACONCN material — adds high-temperature compression molding and long glass-fiber reinforcement, producing a cover that is light, non-brittle and dimensionally stable for decades.</p><h5>Where the differences show up first</h5><ul><li><strong>At the frame:</strong> thin-framed cheap composites and rocking iron frames both generate settlement rings; the deep phenolic flush frame does not.</li><li><strong>Under repeated loading:</strong> low-grade composites creep and crack; iron fractures on impact after corrosion; phenolic holds its rated class.</li><li><strong>At year 10:</strong> iron is rusting, cheap composite is UV-chalked, and the phenolic cover looks essentially unchanged.</li></ul><h5>The honest comparison table</h5><p>Our full eight-row comparison — weight, load, settlement, corrosion, theft, grip, lifespan and lifecycle cost — is on the Comparison page, alongside unretouched field photographs of each material in service. Specifiers are invited to challenge any row.</p>', 'assets/images/comparison/cast-iron-dark-ring.jpg', 'ACONCN Engineering', 4, '2026-07-15T09:00:00'),
(5, 'company', 'SMQ Verifies 40-Tonne and 60-Tonne Proof Loads for AR-700H / AR-900H', 'Independent type-test reports from the Shenzhen Academy of Metrology & Quality Inspection document the load performance behind our main-road and port-duty covers.', '<p>Load-class labels are only as credible as the test behind them. ACONCN''s two flagship round covers — the AR-700H and AR-900H — have been independently type-tested by the Shenzhen Academy of Metrology & Quality Inspection (SMQ), a CMA/CNAS-accredited laboratory.</p><h5>What was tested</h5><ul><li><strong>AR-700H assembly</strong> — 700 mm clear opening in a 100 mm deep frame — verified to a 40-tonne proof load, covering D400–E600 main-road duty.</li><li><strong>AR-900H assembly</strong> — 900 mm clear opening in a 120 mm deep frame — verified to a 60-tonne proof load, the performance demanded by F900 port and airfield zones.</li></ul><h5>Why proof load matters more than a brochure number</h5><p>A type test applies the load through the standard contact block, holds it, and records residual deflection and visible cracking. A cover that merely survives a single press without measuring permanent set tells the specifier nothing. The SMQ reports record both load and deformation behavior — the data a civil engineer can actually design against.</p><h5>Request the documents</h5><p>Full reports, together with the ISO 9001, ISO 14001 and Hong Kong Green Label documents, are available on request through our Certifications page or by email. We encourage tenders and municipal procurement teams to make these reports a mandatory line item.</p>', 'assets/images/certs/smq-60t.jpg', 'ACONCN Quality', 5, '2026-06-30T09:00:00'),
(6, 'industry', 'Why Manhole Covers Sink: Root Causes and the Flush-Mount Fix', 'Cover settlement is usually diagnosed as bad compaction. The real cause is often the cover-frame assembly itself — and the fix belongs at the design stage.', '<p>A sunken manhole is one of the most expensive small defects in a road network: every patch requires traffic management, cutting, reinstatement and compaction, and most patches fail again within two years. Understanding the actual failure mechanism is the first step to stopping the cycle.</p><h5>Four root causes</h5><ol><li><strong>Load transfer through the surface course.</strong> A narrow frame concentrates wheel loads onto the asphalt right at the frame edge, where the pavement is weakest.</li><li><strong>Cover rocking.</strong> Loose manufacturing tolerances let the cover move on its seat; each wheel strike hammers the frame downward.</li><li><strong>Insufficient frame embedment.</strong> Shallow frames sit in the wearing course instead of interlocking with the base course.</li><li><strong>Compaction shadow.</strong> Compaction equipment cannot reach the wedge of material immediately around a frame, leaving a soft ring that settles first.</li></ol><h5>Designing settlement out</h5><p>The ACONCN approach attacks all four: deep skirted frames reach the structural layer; wide flanges spread loads away from the edge; machined seats stop rocking; and the flange geometry gives compaction equipment a flat target. The result is an installation that remains flush — the absence of the familiar dark ring is the visible proof.</p><h5>For asset owners</h5><p>If your reinstatement cycle around covers is shorter than five years, the frame specification — not your paving crew — is the first place to look. We are happy to review your standard detail drawing at no cost.</p>', 'assets/images/comparison/standard-composite.jpg', 'ACONCN Engineering', 6, '2026-06-10T09:00:00'),
(7, 'product', 'Pipe Repair Clamps DN25–DN400: A Selection Guide for Burst Mains', 'When a main bursts, the clock starts. This guide explains how a full-seal bolted clamp restores pressure-rated service — and how to size one in under five minutes.', '<p>A full-seal pipe repair clamp (also called a split coupling or "Haff" coupling) wraps 360° around a damaged pipe and compresses an elastomeric gasket over the defect — no cutting, no welding, no system drain-down in most cases.</p><h5>Sizing in three steps</h5><ol><li><strong>Measure the actual outside diameter</strong> of the pipe, not just its DN designation: older steel and PVC pipes of the same DN can differ in OD.</li><li><strong>Define the defect length:</strong> the clamp must overhang the crack or hole by at least 50–75 mm on each side.</li><li><strong>Match the pressure class:</strong> DN25–DN100 clamps are rated PN16; DN150 and above PN10–PN16 depending on wall build.</li></ol><h5>The ACONCN range</h5><p>Twelve standard bores from DN25 (1″) to DN400 (16″), with ductile-iron epoxy-coated shells, EPDM gaskets (NBR for hydrocarbons on request) and 304 stainless bolts. Tee (tapped) versions can be ordered on DN100 and above for live branch connections. The clamp works across steel, ductile iron, PVC and PE substrates.</p><h5>Field tips</h5><p>Clean the pipe to bright metal or smooth plastic under the gasket; torque bolts in a diagonal sequence to the values printed on the plate; and always carry one size above and below your most common main — the clamp you have at 2 a.m. is the only one that matters.</p>', 'assets/images/products/repair-clamps/dn200.gif', 'ACONCN Pipeline', 7, '2026-05-22T09:00:00'),
(8, 'industry', 'SMC, BMC or Phenolic? Choosing the Right Composite for Heavy-Traffic Covers', 'Three composite families, three very different service envelopes. A materials primer for engineers who need the cover to outlive the road.', '<p>"Fiberglass composite" covers at least three distinct material systems. Confusing them is the fastest way to buy a carriageway-rated label on a footway-grade product.</p><h5>BMC — bulk molding compound</h5><p>Short fibers (often under 6 mm) in a polyester resin paste. Cheap to mold, good surface finish, but the short fiber length limits structural toughness. BMC covers are appropriate for A15–B125 duty; specified higher, they creep and crack under repeated wheel load.</p><h5>SMC — sheet molding compound</h5><p>Longer chopped fibers (25–50 mm) impregnated as a sheet before hot-press molding. SMC delivers a genuine step up in strength and is the workhorse for C250–D400 composite covers when fiber content and press cycle are controlled.</p><h5>Phenolic — glass-fiber reinforced phenolic resin</h5><p>Phenolic resins cure into a rigid, heat-resistant, chemically stable network; combined with long glass-fiber reinforcement under high-temperature compression molding, the result is the highest-performance composite cover family — low creep, excellent fatigue behavior and the material basis of ACONCN''s D400–F900 range.</p><h5>How to tell what you are actually being quoted</h5><p>Ask four questions: resin family, fiber length and content, molding process, and the independent load-test standard. A supplier who can answer all four with documents is selling engineered product; a supplier who answers only "fiberglass" is usually selling BMC at an SMC price.</p><p>The ACONCN line uses glass-fiber reinforced phenolic precisely because our target market — main roads, ports and heavy industry — punishes the gap between a label and a material.</p>', 'assets/images/products/refined/ar-700h.jpg', 'ACONCN Materials', 8, '2026-05-08T09:00:00');

-- ---------- site_content ----------
insert into site_content (id, hero_video_url, about_title, about_text, about_image, contact_title, contact_text, contact_email, contact_phone) values
(1, '', 'Flush with the road — 14 years, zero settlement', 'In December 2012, ACONCN phenolic composite drainage covers were installed on a Shenzhen municipal carriageway. They remain flush with the asphalt today — no settlement "dark ring", no rust, no replacement. That real-world record is why we build deep-flange anti-settlement frames and verify every heavy-duty class with independent SMQ proof-load tests to 40 and 60 tonnes.', 'assets/images/story/story-flush-cover.jpg', 'Contact ACONCN', 'Send us your load class, clear opening and installation zone — engineering replies within 24 hours with a specification and FOB quotation.', 'victor@aconcn.com', '+86 136 0303 8913')
on conflict (id) do update set hero_video_url=excluded.hero_video_url, about_title=excluded.about_title, about_text=excluded.about_text, about_image=excluded.about_image, contact_title=excluded.contact_title, contact_text=excluded.contact_text, contact_email=excluded.contact_email, contact_phone=excluded.contact_phone;

-- Images are served locally (assets/...); keep base url empty
insert into site_settings (key, value) values ('image_base_url', '') on conflict (key) do update set value=excluded.value;

-- Fix product id sequence after explicit inserts
select setval(pg_get_serial_sequence('products','id'), (select max(id) from products));
select setval(pg_get_serial_sequence('certifications','id'), (select max(id) from certifications));
select setval(pg_get_serial_sequence('comparisons','id'), (select max(id) from comparisons));
select setval(pg_get_serial_sequence('news','id'), (select max(id) from news));

commit;

-- After this runs successfully, set Config.USE_LOCAL_DATA = false in assets/js/site-data.js to serve from Supabase.